spring:
  application:
    name: hospital-backend
  liquibase: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  tomcat:
    so-linger: 0

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://hospital-backend-db:5432/
    username: local
    password: local
logging:
  level:
    root: info
---
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: info
