name: Build & Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build JAR with Gradle
        run: |
          ./gradlew clean build -x test
          mv build/libs/hospital-backend-0.0.1-SNAPSHOT.jar app.jar

      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_CR_PASSWORD }}" | docker login hospitalacr.azurecr.io -u ${{ secrets.AZURE_CR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t hospitalacr.azurecr.io/hospital-backend:latest .
          docker push hospitalacr.azurecr.io/hospital-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Await Confirmation for Deployment
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to AKS (Manually Approved)
        run: |
          read -p "Do you want to deploy? (yes/no): " answer
          if [ "$answer" != "yes" ]; then
            echo "Deployment canceled."
            exit 1
          fi

          kubectl set image deployment/backend backend=hospitalacr.azurecr.io/hospital-backend:latest -n iguana
